### ISSUE TITLE
Thoughts on: What Do Industry Practitioners Need?

### ISSUE THREAD

**Issue by kevinrobinson** [fairlearn/fairlearn-proposals#2]
Thanks for sharing such awesome work in the open!  👍   This issue is broadening the discussion a little bit from https://github.com/fairlearn/fairlearn/issues/300#issuecomment-587514778 and https://github.com/fairlearn/fairlearn/issues/238#issuecomment-587132194.  If this is too forward-looking or abstract, and GitHub is the wrong place please let me know :)

As someone who is reasonably familiar with these ML fairness concepts, I was super excited to explore how fairlearn could support folks in discovering fairness issues across different metrics.  👍  The central design critique that came up for me was that it might be promising to explore UX ideas that more directly support exploratory analysis (eg, show me the red flags that come up across any metric all at once, then let me get more details).  That's based on a key assumption that folks won't be able to narrow to one sensitive attribute and one metric up front, and that many fairlearn users will be new to fairness concepts, audits and visualizations.

That might be a bad assumption, but it does come up in the awesome [Improving Fairness in Machine Learning Systems:What Do Industry Practitioners Need? (Holstein et al. 2019](http://www.jennwv.com/papers/fairness-in-practice.pdf)).  For example, it seems like there might be a need for supporting folks in evaluating different fairness metrics and choosing what's most appropriate for their scenario:

> Most of our interviewees’ teams do not currently have fairness metrics against which they can monitor performance and progress.

Some of the other findings that seem particularly relevant in critiquing and thinking through what directions might be promising directions for UX improvements in fairlearn.  I added some bolding:

> Several interviewees expressed needs for support in detecting biases and unfairness prior to deployment, even in cases where **they may not have anticipated all relevant subpopulations or all kinds of fairness issues**

And even more directly:

> “**It’s a little bit of a... manual search** to say, ‘hey, we think this has a bias, let’s go take a look and see if it does,’ which I don’t know is the right approach [...]because **there are a lot of strange ones that you wouldn’t expect [...] that we just accidentally stumbled upon**.”

Both of these seem to indicate there might be a need in doing exploratory analysis, where the design of the tool helps exploring across multiple sensitive features, combinations of them, and multiple error or fairness metrics.  Given that, it's possible that UX changes to add more steps to the wizard might make this 'manual search' process more challenging, which is one scenario that led me to ask these kinds of broader questions.

More generally, I'm curious about how folks are thinking about some of the other opportunities that fairlearn might have to tackle higher-level user needs more directly.  I'm super excited about work aimed at tackling what has come up in the Holstein et al. (2019) paper, and the generative possibilities for UX and design work that's considering those needs directly.  One intuition I have is that this work might involve treating different types of ML problems and different types of fairness issues in less abstracted and more differentiated ways, both in UX and implementation.

I'll be curious to hear what folks think!  And since I don't know y'all very well, it's probably worth saying I have much respect for your work, and thanks for sharing in the open and doing so much to advance the field! 👍

**Comment by MiroDudik** [comment]
I love this thread, but I think that this is a better venue for it!

**Comment by kevinrobinson** [comment]
hi fairlearn pals! :)

From the outside, it sounds like there have been a few ways folks have asked about contributing to the project, which seems great!  And lots of great progress with discussions being open in GitHub, Teams, etc.  I've watched the repo and seen other issues like https://github.com/fairlearn/fairlearn/issues/311#issuecomment-592716247, https://github.com/fairlearn/fairlearn/issues/406#issuecomment-623597208 and that you're having an open developer call later this week.  I have much respect for the efforts in trying to do this kind of work more openly! 👍

At the same time, it's hard to understand if there's a real opportunity to collaborate here, particularly on work that embraces the fundamentally sociotechnical nature of tools, visualizations and algorithms related to fairness.  There's so much awesome work talking about the scope we could be aspiring to here (eg, [Selbst et al. 2019](https://andrewselbst.files.wordpress.com/2019/10/selbst-et-al-fairness-and-abstraction-in-sociotechnical-systems.pdf); [Seo Jo and Gebru 2019](https://arxiv.org/abs/1912.10389)), and I'm hopeful that folks working in this repo might be open to collaborations exploring those kinds of directions.

I separately opened https://github.com/koaning/scikit-fairness/issues/31 as an example of a more specific and scoped proposal.  I know that it can be challenging to collaborate through open source, or with outside contributors in general.  I'm wondering if a productive step might be for folks at MS to describe what a productive outside collaboration might look like, from your perspective?  I'm asking this as a way to respect your perspective and let you control that process, rather than trying to push the work onto you :)

Alternately, if exploring the sociotechnical aspect of this work is beyond the scope of the repo, I can politely close this issue for now.  And as always, thanks for sharing so much of your work in the open! 👍

**Comment by MiroDudik** [comment]
Sorry for dropping the ball on this issue. Frankly, we don't have much experience in collaborative creation of components such as UX flow and case studies, so we've been postponing that part... but we should start moving.

These are a few issues that I'd like to get some clarity about:
* how can we make the UX more modular? do we need to?
* how does one do collaborative UX design?
* how do we set up authoring system around case studies?
  * the easy part: the format should some .py variant of jupyter notebooks, so it plays nicely with github
  * something to discuss: do we want to have explicit notebook authors (at least sometimes?); citation format? (at least sometimes?) 
  * the hard part: how do we ensure quality? our capacity to curate (at least at the beginning) is limited, so how do we prioritize?

For now, I'd like to at least get a sense of what would be a pragmatic solution for the small project of our size. And in particular--where our current contributors are most interested in helping right now. Maybe we can discuss these on the call this week. @kevinrobinson : will you be joining?

**Comment by adrinjalali** [comment]
> the hard part: how do we ensure quality? our capacity to curate (at least at the beginning) is limited, so how do we prioritize?

On this particular issue, I'd say having a diverse set of contributors who feel at home in the project, and together reaching consensus on each issue, would improve the quality of an open source project overall. It may make things a bit slower, but in my experience it ends up being a not too bad of a result :)

**Comment by MiroDudik** [comment]
I think that would be a great way to go... there's a second-order concern how to create and nurture a diverse community of developers (not so easy actually), but we should give it a shot.

**Comment by kevinrobinson** [comment]
@MiroDudik Thanks!  This is super helpful.

Some important things I heard here are:

> we don't have much experience in collaborative creation of components such as UX flow and case studies... how does one do collaborative UX design?

So it sounds like the first priority would be figuring out what will feel comfortable for the current team :)  I think a helpful first step would be checking that I'm aligned with you all about what's important to this project and what success feels like.  There are bits of discussion of this around the repo in doc, threads and proposals, and I've gone through these to try to make sure I am understanding as best I can.  I think this is in the same spirit as https://github.com/fairlearn/fairlearn-proposals/pull/8, where concerns about curation and quality also come up).  But I'm also really trying to help with pulling together some other things like the project roadmap, what will feel like success to the team, etc.  I think it's very hard to talk productively about new UX work without being aligned on those things :)

So one concrete step to move us forward could be to gather a one-page Markdown file (`project-vision.md`), submit that as a pull request, and then leave that open for a week or two so everyone can comment and make sure it's reflecting the team's collective vision.  Then the team can merge that into the README, docs, or wherever folks think is best.  After that, I can propose some specific projects at different scopes within the vision for the project as separate PRs, and interested folks can collectively critique how well they'd fit the project vision and whether they want to collaborate.

[**Here's an demo of what I mean, on a fork**](https://github.com/kevinrobinson/fairlearn/pull/1/files).

I'm happy to kick that off, would it be helpful for me to submit a similar PR to this repo or in the proposal repo?  If so, I'll do that and close this thread.  EDIT: also @MiroDudik yep I can listen in on the call Thursday, and also would love to avoid taking up too much of the group's time :)

**Comment by MiroDudik** [comment]
This is awesome! I think you pulled in the important points really well. Join the call tomorrow and let's follow up. I think that for this kind of a high-level mission document, we can keep it in the main repository under docs--good idea to iterate on it for a week or two and then integrate it into the project website / enhanced docs, which we should roll out in a few weeks (with some early prototypes earlier). See #8 .

**Comment by kevinrobinson** [comment]
@romanlutz @MiroDudik Got it, thanks!  I need a little bit of help though, to figure out what you are asking me to do next in terms of process :)  I am cool with any of these paths, what do you think would be most helpful?

a. wait until https://github.com/fairlearn/fairlearn-proposals/pull/8 lands
b. make these kinds of comments on https://github.com/fairlearn/fairlearn-proposals/pull/8
c. submit a PR on top of https://github.com/fairlearn/fairlearn-proposals/pull/8
d. submit a new PR to the repo with this kind of `project-vision` doc (what was proposed above)

Separately, as another process note @romanlutz has left a bunch of thoughtful comments in my repo on https://github.com/kevinrobinson/fairlearn/pull/1 (sorry for the mixup!).  I've closed that PR since I don't want great conversation about the vision and purpose of this project to be happening in a PR to my personal fork :)  I'll manually move those comments to the main repo based on what you all think is the best next process step, a-d above or something else :)

Thanks! 👍

**Comment by romanlutz** [comment]
#8  is more of a process over the next couple of weeks at least. If you look in the main repo I've started some of the tasks for that already because they're not controversial. The finer points of the structure are still a little fluid, so that's where I could use your input on where you think the vision fits in.

For that reason I'd say option (b), and I think that will result in (d) with a slightly altered destination (not thinkaloud.md but rather docs/vision.rst or something like that)

Looking forward to talking tomorrow, and if this takes longer than the little time we can allot to it we'll just have a follow-up. I'm happy to spend time iterating on this since it matters. Same applies to the UX.

**Comment by kevinrobinson** [comment]
👍 left some comments in https://github.com/fairlearn/fairlearn-proposals/pull/8#pullrequestreview-406913154, and will close this and wait to see how that progresses.
